# Generated by Django 5.2.7 on 2025-10-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('deleted', 'Удалена'), ('assigned', 'Назначена'), ('completed', 'Завершена'), ('status_changed', 'Статус изменен')], max_length=20, verbose_name='Тип действия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Действие с задачей',
                'verbose_name_plural': 'Действия с задачами',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubtaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.subtask', verbose_name='Подзадача')),
            ],
            options={
                'verbose_name': 'Назначение подзадачи',
                'verbose_name_plural': 'Назначения подзадач',
            },
        ),
    ]
