# Generated by Django 5.2.7 on 2025-10-27 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktemplateitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subtask_template_items', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='subtasktemplate',
            name='subtask_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='temp.subtasktemplateitem', verbose_name='Объект подзадачи'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='subtasktemplate',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_templates', to='temp.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AlterUniqueTogether(
            name='subtasktemplate',
            unique_together={('task_template', 'subtask_item')},
        ),
    ]
